# Generated by Django 3.1.6 on 2021-02-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_ciudad_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='zona_turismo',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.paises'),
        ),
    ]
