# Generated by Django 3.1.6 on 2021-02-22 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_auto_20210222_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugares_Turisticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atractivos', models.TextField()),
                ('descripcion', models.TextField(max_length=500)),
                ('clalificacion', models.CharField(max_length=2)),
                ('ubicacion', models.CharField(max_length=100)),
                ('recomendaciones', models.TextField(max_length=500)),
                ('nom_Ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.ciudad')),
            ],
        ),
    ]
