# Generated by Django 3.1.6 on 2021-02-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_lugares_turisticos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='zona_turistica',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
