# Generated by Django 3.1.6 on 2021-02-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_ciudad_zona_turistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares_turisticos',
            name='zona_turistica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zona', to='app_1.ciudad'),
        ),
    ]
