# Generated by Django 3.1.6 on 2021-02-24 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_lugares_turisticos_zona_turistica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugares_turisticos',
            name='nom_Ciudad',
        ),
    ]
